# Generated by Django 4.1.4 on 2022-12-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KasperPhotosSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('phoneNumber', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=80, verbose_name='Email')),
                ('dateRangeLow', models.DateField(verbose_name='Start Date')),
                ('dateRangeHigh', models.DateField(verbose_name='End Date')),
                ('location', models.CharField(max_length=200, verbose_name='Address')),
                ('info', models.CharField(max_length=1000, verbose_name='Describe Your Photoshoot')),
            ],
        ),
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
