# Generated by Django 4.1.4 on 2022-12-12 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KasperPhotosSite', '0003_alter_appointment_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2022, 12, 12, 6, 56, 6, 630075, tzinfo=datetime.timezone.utc))),
                ('blogText', models.TextField(verbose_name='Write Your Blog Post Here')),
            ],
        ),
    ]
