# Generated by Django 4.1.4 on 2022-12-14 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KasperPhotosSite', '0008_alter_blog_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 7, 1, 38, 833153, tzinfo=datetime.timezone.utc)),
        ),
    ]
