# Generated by Django 4.1.4 on 2022-12-14 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KasperPhotosSite', '0009_alter_blog_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dateRangeHigh',
            field=models.CharField(blank=True, max_length=30, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dateRangeLow',
            field=models.CharField(max_length=30, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 10, 3, 27, 155312, tzinfo=datetime.timezone.utc)),
        ),
    ]
