# Generated by Django 4.1.4 on 2022-12-14 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KasperPhotosSite', '0010_alter_appointment_daterangehigh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 10, 13, 2, 977391, tzinfo=datetime.timezone.utc)),
        ),
    ]
