# Generated by Django 4.1.4 on 2022-12-14 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KasperPhotosSite', '0011_alter_blog_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 10, 37, 35, 112265, tzinfo=datetime.timezone.utc)),
        ),
    ]
